
// !Exercise 5

const usingPromise = async () => {
	try {
		const promiseResult = await newPromise;
		console.log(promiseResult, "Exercise 4");
	} catch (error) {
		console.log(error);
	}
};


